Clinica\AppBundle\Entity\Cita:
    type: entity
    table: cita
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        fecha:
            type: date
        hora:
            type: time
            
    manyToOne:
        cliente:
            targetEntity: Cliente
            joinColumn: cliente_id
            referencedColumnName: id
        doctor:
            targetEntity: Doctor
            joinColumn: doctor_id
            referencedColumnName: id
    lifecycleCallbacks: {  }
