Clinica\AppBundle\Entity\Cita:
    type: entity
    table: null
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        fecha:
            type: date
        hora:
            type: time
    lifecycleCallbacks: {  }
