Clinica\AppBundle\Entity\Doctor:
    type: entity
    table: null
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        nombre:
            type: string
            length: '60'
        apellidos:
            type: string
            length: '120'
        cedula:
            type: string
            length: '25'
        especialidad:
            type: string
            length: '25'
        telefono:
            type: string
            length: '20'
        precioConsulta:
            type: float
    lifecycleCallbacks: {  }
