Clinica\AppBundle\Entity\Vacaciones:
    type: entity
    table: null
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        fecInicio:
            type: date
        fecFinal:
            type: date
            
    manyToOne:
        doctor:
            targetEntity: Doctor
            joinColumn: doctor_id
            referencedColumnName: id
    lifecycleCallbacks: {  }
