security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext
        Clinica\AppBundle\Entity\Usuarios:
            algorithm: sha1
            encode_as_base64: false
            iterations: 1
        
     

    role_hierarchy:
      ROLE_ADMIN:       ROLE_USER
      ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]
      ROLE_PREMIUM:     [ ROLE_REGISTRADO ]
    
    providers:
        users:
            entity: {class: ClinicaAppBundle:Usuarios, property: username }
    
    firewalls:
        secured_area:
            pattern: ^/clinica/    
            form_login:
                login_path: /clinica/login
                check_path: /clinica/login_check
            logout: 
                path: /clinica/logout
                target: /clinica
                invalidate_session: false

    
    access_control:
        - {path: ^/secured, roles: ROLE_ADMIN }
        - {path: /clinica, roles: ROLE_USER }
        
                
    #providers:
    #    in_memory:
    #        memory:
    #            users:
    #                user:  { password: userpass, roles: [ 'ROLE_USER' ] }
    #                admin: { password: adminpass, roles: [ 'ROLE_ADMIN' ] }
  
   
           #anonymous: ~
            #http_basic:
            #    realm: "Secured Demo Area"


