clinica_app_homepage:
    pattern:  /clinica/
    defaults: { _controller: ClinicaAppBundle:Default:index }
    
nuevo_cliente:
    pattern: /clientes/newCliente
    defaults: {_controller: ClinicaAppBundle:Cliente:newCliente }

mostrar_cliente:
    pattern: /clientes/listaCliente
    defaults: {_controller: ClinicaAppBundle:Cliente:listaClientes}

nuevo_doctor:
    pattern: /doctores/newDoctor
    defaults: {_controller: ClinicaAppBundle:Doctor:newDoctor }
    
mostrar_doctor:
    pattern: /doctores/listaDoctor
    defaults: {_controller: ClinicaAppBundle:Doctor:listaDoctor}

nuevo_usuario:
    pattern: /admin/newUsuario
    defaults: {_controller: ClinicaAppBundle:Usuario:newUsuario }
    
usuario_login:
    pattern: /usuario/login
    defaults: { _controller: ClinicaAppBundle:Usuario:login }

usuario_login_check:
    pattern: /usuario/login_check

usuario_logout:
    pattern: /usuario/logout