#clinica_app_homepage:
#    pattern:  /clinica/
#    defaults: { _controller: ClinicaAppBundle:Default:index }
    
nuevo_cliente:
    pattern: /clientes/newCliente
    defaults: {_controller: ClinicaAppBundle:Cliente:newCliente }

mostrar_cliente:
    pattern: /clientes/listaCliente
    defaults: {_controller: ClinicaAppBundle:Cliente:listaClientes}

nuevo_doctor:
    pattern: /doctores/newDoctor
    defaults: {_controller: ClinicaAppBundle:Doctor:newDoctor }
    
mostrar_doctor:
    pattern: /doctores/listaDoctor
    defaults: {_controller: ClinicaAppBundle:Doctor:listaDoctor}

nuevo_usuario:
    pattern: /admin/newUsuario
    defaults: {_controller: ClinicaAppBundle:Usuario:newUsuario }
    
login:
    pattern: /clinica/login
    defaults: { _controller: ClinicaAppBundle:Default:login }
    
login_signup:
    pattern:  /signup
    defaults: { _controller: ClinicaAppBundle:Default:signup }

logout:
    pattern: /clinica/logout
    defaults: { _controller: ClinicaAppBundle:Default:logout }